### ISSUE TITLE
BUG: barely visible text in search bar on appstore website 

### ISSUE THREAD

**Issue by axtloss** [bottlesdevs/website#32]
when going to the [appstore site](https://usebottles.com/appstore/) using dark mode, the text in the search bar is barely visible:
![image](https://user-images.githubusercontent.com/60044824/177876890-f4426f56-a4c7-491f-895b-e18a57065f81.png)

**Comment by TheEvilSkeleton** [comment]
Hmm... Looks like I can still reproduce it.
