### ISSUE TITLE
Update screenshots with Material U

### ISSUE THREAD

**Issue by suwermave** [bottlesdevs/website#40]
The website is very colorful in contrast to application screenshots.
**Proposal:**
We could use Material U extension to color screenshots for each specific row.
Here are some examples of how would it look like:
![1](https://user-images.githubusercontent.com/50447661/192164764-5c098c76-e3e3-4be3-be9e-6f80e2c98329.png)
![2](https://user-images.githubusercontent.com/50447661/192164791-0ab8725f-56f9-44f7-acc3-4c80bfa4e599.png)
![3](https://user-images.githubusercontent.com/50447661/192164897-7057be50-61b8-4e6a-8596-5114b144740b.png)
![4](https://user-images.githubusercontent.com/50447661/192164917-456c2a4e-67fb-42b3-9f8d-cc8997835462.png)

**Comment by mirkobrombin** [comment]
While this is very visually beautiful, Bottles wants to be a GNOME standard faithful application and for this reason the screenshots must follow the Adwaita theme and colors (as well as the officially supported theme).

**Comment by axtloss** [comment]
This would also give the impression that Bottles supports changing the colour scheme, which it doesn't, so it's not really a good idea to add it to the website
