### ISSUE TITLE
Missing RSS feed

### ISSUE THREAD

**Issue by foo-dogsquared** [bottlesdevs/website#56]
The RSS feed link from the footer links to a non-existent feed. I would like to have an RSS feed to closely follow the project.
The following is a recording just to see the experience.

[Screencast from 2023-05-15 22-25-25.webm](https://github.com/bottlesdevs/website/assets/34962634/c363362d-7553-410f-aec2-524a998847d6)

**Comment by GabsEdits** [comment]
With the latest update, it seems as the issue has been fixed

**Comment by mirkobrombin** [comment]
I confirm, it is fixed now https://usebottles.com/rss.xml
