### ISSUE TITLE
Social icons are displayed above installer manifest popup

### ISSUE THREAD

**Issue by riQQ** [bottlesdevs/website#59]
Steps to reproduce:
- Go to https://usebottles.com/appstore/
- Scroll down far enough so *Magic: The Gathering Arena* and the social buttons in the footer are visible
- Click the down arrow next to *Magic: The Gathering Arena* and click *Show installer* in the menu 

Browser: Firefox 125.0.3

![screenshot website showing the bug](https://github.com/bottlesdevs/website/assets/3404787/9ec59102-acd2-4459-8573-26cd3df44551)

**Comment by mirkobrombin** [comment]
fixed on new version
