### ISSUE TITLE
RSS for the blog?

### ISSUE THREAD

**Issue by ldsands** [bottlesdevs/website#8]
I'm no developer but I would love to see a RSS feed implemented for the blog so I can keep up on the changes!

Thank you for all of your work on bottles. It makes my life quite a bit easier.

**Comment by mirkobrombin** [comment]
> I'm no developer but I would love to see a RSS feed implemented for the blog so I can keep up on the changes!

This https://usebottles.com/feed ?

> Thank you for all of your work on bottles. It makes my life quite a bit easier.

😊

**Comment by ldsands** [comment]
Oops I guess I've become too reliant on [this browser extension](https://github.com/shevabam/get-rss-feed-url-extension). The extension didn't find it and I didn't see a rss link so I assumed there wasn't one. I should have done a quick search in the repo.

Thank you!

**Comment by mirkobrombin** [comment]
> Oops I guess I've become too reliant on [this browser extension](https://github.com/shevabam/get-rss-feed-url-extension). The extension didn't find it and I didn't see a rss link so I assumed there wasn't one. I should have done a quick search in the repo.
> 
> Thank you!

Maybe we should put the link somewhere on the website :D

**Comment by ldsands** [comment]
I added the RSS link and logo in [this pull request](https://github.com/ldsands/website/pull/1). Be aware that I can't click the logos to get those links in either Edge or Firefox. I don't know almost anything about js (or git/github for that matter) so I'll leave that to someone else.

**Comment by mirkobrombin** [comment]
> 

Oh fine, let me fix it
